name: setup-python-poetry-action
description: Setup python with Poetry, making sure to cache the dependencies using poetry.lock as a hash
author: "Aydin Abiar"
branding:
  icon: settings
  color: blue

inputs:
  python-version:
    description: Python version to use

runs:
  using: composite
  steps:
      # Could cache ~/.local/bin/poetry, for optimization and only install if not found
      - uses: snok/install-poetry@v1

      - name: Set up Python and cache poetry
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'poetry'

      - run: poetry env use ${{ inputs.python-version }}
        shell: bash
        # only if the python version is given as input
        if: "${{ inputs.python-version != '' }}"

      - run: poetry install --no-interaction
        shell: bash

      - name: "Python verison in poetry"
        run: poetry run python --version
        shell: bash