name: setup-python-poetry-action
description: Setup python with Poetry, making sure to cache the dependencies using poetry.lock as a hash
author: "Aydin Abiar"
branding:
  icon: settings
  color: blue

inputs:
  python-version:
    description: Python version to use
  poetry-version:
    description: Poetry version to use
    required: true

runs:
  using: composite
  steps:
      # Not needed for the rest of the action, but declutter/simplify the caller job
      - name: Checkout repository
        uses: actions/checkout@v4

      #----------------------------------------#
      #       Install & configure Poetry       #            
      #----------------------------------------#
      # set inputs.python-version to the latest python version
      - name: Set Python Version if version number not provided or is "latest"
        shell: bash
        run: |
            latest_python=$(curl -s https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json | jq -r '.[0].version')
            # output is like 3.14.0-alpha.5 so we need to cut it to 3.14 (for example)
            latest_python=$(echo $latest_python | cut -d '.' -f 1,2)
            echo "python_version=$latest_python" >> $GITHUB_ENV
        if: inputs.python-version == ''

      - name: Set Python Version if version number provided
        shell: bash
        run: echo "python_version=${{ inputs.python-version }}" >> $GITHUB_ENV
        if: "${{ ! (inputs.python-version == '' || inputs.python-version == 'latest') }}"

      - name: Debug
        shell: bash
        run: echo "Python version - ${{ env.python_version }}"

      - name: Load cached .local
        id: cached-dotlocal
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: dotlocal-os_${{ runner.os }}-poetry${{ inputs.poetry-version }}-py${{ env.python_version }}


      - name: Print cache hit or miss
        run: echo "Cache dotlocal ${{ steps.cached-dotlocal.outputs.cache-hit }}"
        shell: bash

      - uses: snok/install-poetry@v1
        with:
          version: ${{ inputs.poetry-version }}

      #------------------------------------------------#
      #       Set-up python & cache dependencies       #
      #------------------------------------------------#
      - name: Set up Python and cache poetry
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }} # can handle '' by itself
          cache: 'poetry'

      - name: Print output python version
        run: echo "OUTPUT PYTHON VERSION ${{ steps.setup-python.outputs.python-version }}"
        shell: bash

      # By default, poetry wil use the minimal required python in your .toml, so we need to manually set the python version
      # https://github.com/actions/setup-python/issues/846
      - run: poetry env use ${{ inputs.python-version }}
        shell: bash
        # only if the python version is clearly specified
        if: "${{ inputs.python-version != '' }}"

      #------------------------------------------------------------#
      #       Load cash dependencies or Install from scratch       #
      #------------------------------------------------------------#
      - run: poetry install --no-interaction
        shell: bash

      - name: "Python verison in poetry"
        run: poetry run python --version
        shell: bash