name: setup-python-poetry-action
description: Setup python with Poetry, making sure to cache the dependencies using poetry.lock as a hash
author: "Aydin Abiar"
branding:
  icon: settings
  color: blue

inputs:
  python-version:
    description: Python version to use
  poetry-version:
    description: Poetry version to use

runs:
  using: composite
  steps:
      # Not needed for the rest of the action, but declutter/simplify the caller job
      - name: Checkout repository
        uses: actions/checkout@v4

      #----------------------------------------#
      #       Install & configure Poetry       #            
      #----------------------------------------#
      - name: Set up Python (temporary)
        id: setup-python-temp
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
        if : inputs.python-version == ''

      - name: Set resolved Python version
        id: get-python-version
        shell: bash
        run: |
          if [[ -n "${{ inputs.python-version }}" ]]; then
            echo "python_version=${{ inputs.python-version }}" >> $GITHUB_ENV
          else
            echo "python_version=$(python --version | cut -d ' ' -f2)" >> $GITHUB_ENV
          fi

      - name: Set poetry version to latest if not specified
        shell: bash
        run: |
          if [[ -n "${{ inputs.poetry-version }}" && "${{ inputs.poetry-version }}" != "latest" ]]; then
            echo "poetry_version=${{ inputs.poetry-version }}" >> $GITHUB_ENV
          else
            latest_poetry=$(curl -s https://pypi.org/pypi/poetry/json | jq -r '.info.version')
            echo "poetry_version=$latest_poetry" >> $GITHUB_ENV
          fi

      - name: Load cached .local
        id: cached-dotlocal
        uses: actions/cache@v4
        with:
          path: ~/.local
          key: dotlocal-os_${{ runner.os }}-poetry${{ env.poetry_version }}-py${{ env.python_version }}

      - uses: snok/install-poetry@v1
        with:
          version: ${{ env.poetry_version }}
        if: steps.cached-dotlocal.outputs.cache-hit != 'true'

      #------------------------------------------------#
      #       Set-up python & cache dependencies       #
      #------------------------------------------------#
      - name: Set up Python and cache poetry
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.python_version  }}
          cache: 'poetry'

      # By default, poetry wil use the minimal required python in your .toml, so we need to manually set the python version
      # https://github.com/actions/setup-python/issues/846
      - run: poetry env use ${{ env.python_version }}
        shell: bash

      #------------------------------------------------------------#
      #       Load cash dependencies or Install from scratch       #
      #------------------------------------------------------------#
      - run: poetry install --no-interaction
        shell: bash
